// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiTBvIn7NofN026K_JLAdyL_XgEb6iylY',
    appId: '1:745946017392:web:fe4914a2eb42bcf9cf8eb5',
    messagingSenderId: '745946017392',
    projectId: 'darpy-a247d',
    authDomain: 'darpy-a247d.firebaseapp.com',
    storageBucket: 'darpy-a247d.firebasestorage.app',
    measurementId: 'G-6WLQ3BLGRT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBADO7GXubTfAH1QjjvYLh2x4hOteeNSQc',
    appId: '1:745946017392:android:e7968428bf244516cf8eb5',
    messagingSenderId: '745946017392',
    projectId: 'darpy-a247d',
    storageBucket: 'darpy-a247d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM7rGytjGd8B0kpPT2MSqJhXBj7o68vNM',
    appId: '1:745946017392:ios:e62ad6d366a8eea2cf8eb5',
    messagingSenderId: '745946017392',
    projectId: 'darpy-a247d',
    storageBucket: 'darpy-a247d.firebasestorage.app',
    iosBundleId: 'com.example.kidsTransport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM7rGytjGd8B0kpPT2MSqJhXBj7o68vNM',
    appId: '1:745946017392:ios:e62ad6d366a8eea2cf8eb5',
    messagingSenderId: '745946017392',
    projectId: 'darpy-a247d',
    storageBucket: 'darpy-a247d.firebasestorage.app',
    iosBundleId: 'com.example.kidsTransport',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiTBvIn7NofN026K_JLAdyL_XgEb6iylY',
    appId: '1:745946017392:web:25f4532d52790bf1cf8eb5',
    messagingSenderId: '745946017392',
    projectId: 'darpy-a247d',
    authDomain: 'darpy-a247d.firebaseapp.com',
    storageBucket: 'darpy-a247d.firebasestorage.app',
    measurementId: 'G-PW1B2TQP6M',
  );
}
